[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "cd backend && npm ci --only=production"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
PORT = "3001"
