[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "cd backend && npm ci --only=production",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
PORT = "3001"

# 多服务配置
[services.backend]
buildCommand = "cd backend && npm ci --only=production"
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"
port = 3001

[services.frontend]
buildCommand = "cd frontend && npm ci && npm run build"
outputDir = "frontend/build"
environment = "static"
