[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'This is a monorepo with multiple services'"

# Backend service
[[services]]
name = "backend"
root = "backend"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Frontend service
[[services]]
name = "frontend"
root = "frontend"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.variables]
REACT_APP_API_URL = "https://electricityyierbubu-production.up.railway.app/api"